### ISSUE TITLE
css is not generated

### ISSUE THREAD

**Issue by arthurvaverko** [mkwtys/icontype#49]
using the cli
icontype ./*.svg -f=bks-icons -c=my-icon -p=./font --normalize --out-dir=./font

but the output only includes font and not the css files...

**Comment by mkwtys** [comment]
@arthurvaverko yes, generate font only.
use template/template-dest to generate css.

```sh
--template <template source> --template-dest <template output directory>
```

template sample:
https://github.com/mkwtys/icontype/blob/master/template/icontype.css
